"""add page and char count

Revision ID: d4cded3476a4
Revises: 2c316f910ab1
Create Date: 2026-09-24 15:32:18.327128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4cded3476a4'
down_revision: Union[str, None] = '2c316f910ab1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('page_count', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('character_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'character_count')
    op.drop_column('documents', 'page_count')
    # ### end Alembic commands ###
